---
title: "final dataframe"
author: "Sharujan Suthakaran, Aaron Eidenmüller"
date: "05.Juli 2023"
---

```{r}
breast_exp_mean <- apply(breast_prism.exp, 2, mean)

achilles.genes.adj <- as.data.frame(p.adjust(unlist(achilles.genes), method = "fdr"))

rownames(achilles.genes.adj) <- rownames(achilles.genes)

w.genes.cancer <- names(breast.achilles.mean)[which(breast.achilles.mean<(-1))]

names.target <- as.vector(targets.treat$name)

targets.treat <- prism.treat_subset[which(prism.treat_subset$`rownames(prism.treat)`%in%colnames(breast_prism_lowest)),]

breast_cnv.mean <- apply(breast_prism.cnv, 2, mean)


#class(hallmarks.geneSym)

hallmarks.data <- as.data.frame(hallmarks.geneSym)

input_string <- rownames(hallmark.genes)[which(hallmark.genes$hallmarks.geneSym%in%w.genes.cancer[1])]

##makes hallmark dataset suitable for us

extract_transform <- function(input_string) {
  modified_string <- gsub("^HALLMARK_", "", input_string)
  split_string <- strsplit(modified_string, "_")[[1]]
  capitalized_words <- sapply(split_string, function(word) {
    paste0(toupper(substring(word, 1, 1)), substring(word, 2))
  })
  transformed_string <- paste(capitalized_words, collapse = " ")
  
  return(transformed_string)
}


```


```{r}

Wgene.krebs <- data.frame()

for (gene_name in w.genes.cancer) {
    frequency_value <- hist.targets[hist.targets$genes == gene_name, "Freq"]
    achilles_value <- breast.achilles.mean[gene_name]
    exp_value <- breast_exp_mean[gene_name]
    cnv_value <- breast_cnv.mean[gene_name]
    p_value <- achilles.genes.adj[gene_name,]
    if (gene_name%in%hallmark.genes$hallmarks.geneSym){
      hall.output <- rownames(hallmark.genes)[which(hallmark.genes$hallmarks.geneSym%in%gene_name)]
      hall.transform <- extract_transform(hall.output)
      hallmark <- paste(hall.transform, collapse = ", ")
    }
      else {
        hallmark <- c("none")
      }
    if (gene_name%in%breast_prism.snv$Hugo_Symbol){
      mut.pos <- which(gene_name%in%breast_prism.snv$Hugo_Symbol)
      mutation <- as.vector(breast_prism.snv$Variant_Classification[mut.pos])
    }
      else {
        mutation <- c("none")
      } 
    if (gene_name%in%targets.treat$target){
      names <- paste(names.target[which(targets.treat$target==gene_name)], collapse = ", ")
      treatments <- trimws(names, whitespace = "right")
    }
      else {
        treatments <- c("none")
      }
      
    new_row <- c(frequency_value, achilles_value, exp_value, cnv_value, p_value, treatments, mutation, hallmark)
  if (gene_name == w.genes.cancer[1]) {
    Wgene.krebs <- new_row
  } 
    else {
    Wgene.krebs <- rbind(Wgene.krebs, new_row)
  }
}

rownames(Wgene.krebs) <- w.genes.cancer

colnames(Wgene.krebs) <- c("Frequency in list.targets", "mean prism.achilles", "mean prism.exp", "cnv value", "p-value from achilles.genes.adj", "treatments", "mutation", "hallmark")
```

```{r}

geneSearchEngine <- function(x) {
  gene_name <- x
  cat("Searching for:", gene_name, "\n")
  
  achilles_value <- breast.achilles.mean[gene_name]
  exp_value <- breast_exp_mean[gene_name]
  cnv_value <- breast_cnv.mean[gene_name]
  
  if (gene_name %in% hist.targets$genes) {
    frequency_value <- hist.targets[hist.targets$genes == gene_name, "Freq"]
  } else {
    frequency_value <- "none"
  }
 
  
  if (gene_name %in% hallmark.genes$hallmarks.geneSym) {
    hall.output <- rownames(hallmark.genes)[which(hallmark.genes$hallmarks.geneSym %in% gene_name)]
    hall.transform <- extract_transform(hall.output)
    hallmark <- paste(hall.transform, collapse = ", ")
  } else {
    hallmark <- "none"
  }
  
  if (gene_name %in% breast_prism.snv$Hugo_Symbol) {
    mut.pos <- which(gene_name %in% prism.snv$Hugo_Symbol)
    mutation <- as.vector(prism.snv$Variant_Classification[mut.pos])
  } else {
    mutation <- "none"
  }
  
  if (gene_name %in% breast_prism.snv$Hugo_Symbol) {
    variant.anno <- which(gene_name %in% breast_prism.snv$Hugo_Symbol)
    annotation.var <- as.vector(breast_prism.snv$Variant_annotation[variant.anno])
  } else {
    annotation.var <- "none"
  }
  
  if (gene_name %in% prism.treat_subset$target) {
    names <- paste(names.target[which(targets.treat$target==gene_name)], collapse = ", ")
    treatments <- trimws(names, whitespace = "right")
  } else {
    treatments <- "none"
  }
  
  cat("Frequency Value:", frequency_value, "\n")
  cat("Achilles Value:", achilles_value, "\n")
  cat("Exp Value:", exp_value, "\n")
  cat("Cnv Value:", cnv_value, "\n")
  cat("Mutation:", mutation, "\n")
  cat("Hallmark:", hallmark, "\n")
  cat("Variant Annotation:", annotation.var, "\n")
  cat("Treatments:", treatments, "\n")
  cat("\n")
}

geneSearchEngine("ESR1")



```
