---
title: "  "
date: " "
bibliography:
csl: 
geometry: "margin=2.3cm"
linestretch: 1.15
output: 
  pdf_document:
    number_sections: true
---




Ich würde mit bookdown schreiben https://bookdown.org/yihui/rmarkdown-cookbook/formatting.html
Da wird formatieren deutlich einfacher

Bei dem angefangenen Frame habe ich mich stark an den Vorgaben des Essays orientiert. Wir könnten dann, wenn wir das mit bookdown machen, das IPMB Tex Template verwenden 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Title page mit Titel, Gruppennummer und Gruppenmitgliedern

#Abstract

Table of contents
+
Abbreviations


#Introduction



# Materials and Methods

##Data 

### Prism Datasets  

**Prism:** effect of the treatment (columns) on cell growth of the cell lines (rows); includes drug, dosage and assay used

**Prism.treat:** for each treatment (rows) further information on the treatment and drug

**Prism.cl:** contains information about the different celllines    
*if we search after "breast" in the column lineage we get our 22 celllines*

### Cellline Datasets  

**Prism.exp:** contains levels of gene expression. Celllines (rows) and genes (columns)

**Prism.cnv:** contains copy number levels of genes. Normal is CN = 2. Gene names (rows) and celllines (columns)

**Prism.snv:** marks mutation in the different celllines als functional or nonfunctional to the cancer.

**Prism.achilles:** has information on how important a gene is for cell survival. Was generated using knockdown celllines. Gene names (rows) and celllines (colums)
   

## Data clean up/Filtering
Show distributions after cleanup
   
##Clustering
kmeans

##Dimension reduction  
UMAP

##statistical test
Wilcoxson test
0.05 alpha
p adjust needed

##Lineare Regression

#Results
First include positiv results; if space is left include negativ results: UMAP, K means clustering, promoting drugs
describe goal, describe process, describe outcome
##List of inhibitory drugs


##Gen search engine

##Dataframe for targets involving genes

##Linear regression
Perform drug by drug to avoid weird plot

#Discussion
Search for papers mentioning certain genes found in the targets of the inhibitory drugs or 


#References
