```{r}
load("C:/Users/aaron/Desktop/Studium/4. Semester/Bioinfo/prism_datasets.rda")
load("C:/Users/aaron/Desktop/Studium/4. Semester/Bioinfo/cellline_datasets.rda")

```

```{r}

```

How about a kmeans clustering? (cell lines)
```{r}
wss.prism <- sapply(1:10, function(x) kmeans(breast_prism_imp, x)$tot.withinss)

plot(1:10, wss.prism, type = "b", xlab = "N of clusters", ylab = "Total within sum of square")
```

```{r}
wss.prism <- sapply(1:10, function(x) kmeans(t(breast_prism_lowest), x)$tot.withinss)

plot(1:10, wss.prism, type = "b", xlab = "N of clusters", ylab = "Total within sum of square")

```
not very helpful...

```{r}
prism.sd <- apply(breast_prism_imp, 2, sd)

prism.rel <- breast_prism_imp[, which(prism.sd>1)]

D <- dist(t(prism.rel))
library(cluster)
sil <- vector()

for (k in 1:60) {
  km <- kmeans(x = t(prism.rel), centers = k, iter.max = 40)
  s <- silhouette(km$cluster, D)
  sil <- c(sil, mean(s))
}
plot(1:60,sil)
```
```{r}
D <- dist(t(breast_prism_lowest))
library(cluster)
sil <- vector()

for (k in 1:20) {
  km <- kmeans(x = t(breast_prism_lowest), centers = k, iter.max = 40)
  s <- silhouette(km$cluster, D)
  sil <- c(sil, mean(s))
}
plot(1:20,sil)
```


The maximal QTR stage has been exceeded. This means we have to reduce the data.

```{r} 
#trying to do the clustering on the whole prism data
wss.prism <- sapply(1:10, function(x) kmeans(t(prism_imp), x)$tot.withinss)

plot(1:10, wss.prism, type = "b", xlab = "N of clusters", ylab = "Total within sum of square")



```

```{r}
unique(prism.treat$phase)
```
```{r}
install.packages("readxl")
load("C:/Users/aaron/Desktop/Studium/4. Semester/Bioinfo/Mappe2.xlsx")
```



```{r}
#try to identify the treatments with low sd

prism.sd <- apply(breast_prism_imp, 2, sd)

prism.rel <- breast_prism_imp[, which(prism.sd>1.5)]# relevant treatments

wss.prism <- sapply(1:10, function(x) kmeans(breast_prism_imp, x)$tot.withinss)

plot(1:10, wss.prism, type = "b", xlab = "N of clusters", ylab = "Total within sum of square")
```





```{r}
km.test <- kmeans(x = t(breast_prism_imp), centers = 11, iter.max = 20)
```


Now I will try something. I want to know drugs that show a high effect on some cell lines. For this I will firstly delete the columns of oncological drugs as there were shown to have a effect on cancer
```{r}

lowest_cl <- colnames(breast_prism_imp)%in%rownames(lowest_mean_duplicate)
breast_prism_lowest <- breast_prism_imp[,lowest_cl]

dim(breast_prism_lowest)

```
```{r}
library(readxl)
cancer.therapy <- readxl::excel_sheets("C:/Users/aaron/Desktop/Studium/4. Semester/Bioinfo/Mappe3.xlsx")

read_excel("C:/Users/aaron/Desktop/Studium/4. Semester/Bioinfo/Mappe3.xlsx")

print(cancer.therapy)
```


























































































































