```{r}
####################################
##### CORRELATION DRUG ~ CONC ###### Luis
####################################
##############
### BREAST ###
##############
drugnames_b <- sub("::.*", "", colnames(breast_prism_imp))
concentration_b <- as.numeric(sub(".*::(.*?)::.*", "\\1", colnames(breast_prism_imp)))
names_conc_drug_b <- sub("::.*", "", sub("::", ":", colnames(breast_prism_imp)))
colMeans_breast <- apply(breast_prism_imp, 2, mean)
duplicate_drugs_b <- unique(drugnames)
df_nam_con_mean_b <- data.frame(colMeans_breast, drugnames_b, concentration_b, names_conc_drug_b)
highest_cor_b <- data.frame()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    if (length(act_rows_b) > 2) {
        cor_b <- cor(act_df_b$concentration_b, act_df_b$colMeans_breast, method = "pearson")
        new_row <- data.frame(drugname = duplicate_drugs_b[i], correlation = cor_b)
        highest_cor_b <- rbind(highest_cor_b, new_row)
    }
}
```

```{r}
###############################
###### LINEAR REGRESSION ###### Luis
###############################
##############
### BREAST ###
##############
regression_list_b <- list()
r_squared_b <- c()
p_value_b <- c()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    if (length(act_rows_b) > 3) {
        act_reg_b <- lm(colMeans_breast ~ concentration_b, data = act_df_b)
        act_residuals_b <- act_reg_b$residuals
        act_shapiro_b <- shapiro.test(act_residuals_b)
        act_plot_b <- data.frame(concentration_b = act_df_b$concentration, colMeans = act_df_b$colMeans_breast)
        regression_list_b[[i]] <- list(Summary_reg = summary(act_reg_b), Model = act_reg_b, Residuals = act_residuals_b, R_squared = summary(act_reg_b)$r.squared, Plotdata = act_plot_b, Shapiro_test = act_shapiro_b, prediction = act_df_b)
        names(regression_list_b)[i] <- duplicate_drugs_b[i]
        r_squared_b <- c(r_squared_b, summary(act_reg_b)$r.squared)
        p_value_b <- c(p_value_b, act_shapiro_b$p.value)
    }
}
testname <- "BRD-K99383816-001-03-5"
```
```{r}
#######################
### PLOT REGRESSION ###
#######################
plot_reg <- function(drugname) {
    position <- which(drugname == names(regression_list_b))
    #### Summary model ####
    act_summary_b <- regression_list_b[[position]][[2]]
    #### Model ####
    act_model_b <- regression_list_b[[position]][[1]]
    #### Shapiro-Wilk test ####
    act_shapiro <- regression_list_b[[position]][[6]]

    #### Metadata ####
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
    list(a = format(unname(coef(act_model_b)[1]), digits = 2),
         b = format(unname(coef(act_model_b)[2]), digits = 2),
         r2 = format(act_model_b$r.squared, digits = 3)))
    as.character(as.expression(eq))

    #### Plot the regression ####
    ggplot <- ggplot(data = regression_list_b[[position]][[5]], aes(x = concentration_b, y = colMeans)) +
        stat_smooth(method = "lm", formula = y ~ x, geom = "smooth") +
        geom_point() +
        labs(x = "Concentration", y = "Mean of PRISM score", title = paste("Regression for:", drugname)) +
        annotate("text", x = 6.5, y = 1.5, label = eq, size = 3) +
        annotate("text", x = 6.5, y = 1, label = paste("Shapiro-Wilk normality test for Residuals:", "\n", "W =", round(act_shapiro$statistic, 3), "|  p-value =", format(act_shapiro$p.value, scientific = TRUE)), size = 3)

    return(ggplot)
}
```

```{r}
#######################
### PREDICTION TOOL ###
#######################
prediction_tool <- function(drugname, conc_values) {

    position <- which(drugname == names(regression_list_b))

    #### Prediction ####
    act_model_b <- regression_list_b[[position]][[2]]
    new_data <- data.frame(concentration_b = conc_values) 
    act_shapiro <- regression_list_b[[position]][[6]]
    colMeans <- predict(act_model_b, newdata = new_data)

    cat("-------------------------------------------------------\n")
    cat("Concentrations:\n")
    print(setNames(conc_values, c(1:length(conc_values))))
    cat("Predicted Prism Scores:\n")
    print(round(colMeans, 3))
    cat("-------------------------------------------------------\n")

    ### Combine the data ###
    act_newdata <- cbind(new_data, colMeans)
    act_newdata <- cbind(act_newdata, level = c(replicate(length(new_data), "predicted")))
    hold_df <- cbind(regression_list_b[[position]][[5]], level = c(replicate(length(regression_list_b[[position]][[5]]$concentration_b), "original")))
    comb_df <- rbind(hold_df, act_newdata)
    comb_df[,3] <- as.factor(comb_df[,3])
    col_df <- c(predicted = "coral2", original = "black")

    ### Metadata ###
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
    list(a = format(unname(coef(act_model_b)[1]), digits = 2),
         b = format(unname(coef(act_model_b)[2]), digits = 2),
         r2 = format(summary(act_model_b)$r.squared, digits = 3)))
    as.character(as.expression(eq))

    ### Plot the prediction ###
    ggplot <- ggplot(data = comb_df, aes(x = concentration_b, y = colMeans, color = level)) +
        stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", color = "steelblue") +
        geom_point() +
        labs(x = "Concentration", y = "Mean of PRISM score", title = paste("Regression for:", drugname), color = "") +
        scale_color_manual(values = col_df) +
        annotate("text", x = 6.5, y = 1.5, label = eq, size = 3) +
        annotate("text", x = 6.5, y = 1, label = paste("Shapiro-Wilk normality test for Residuals:", "\n", "W =", round(act_shapiro$statistic, 3), "|  p-value =", format(act_shapiro$p.value, scientific = TRUE)), size = 3)

    return(ggplot)
}
```