```{r}
#####################################
###### IMPORT LIBRARIES & DATA ######
#####################################
library(ggplot2) #install.packages("ggplot2")
library(umap) #install.packages("umap")
library(readxl) #install.packages("readxl")
library(scales) #install.packages("scales")
library(dplyr)  #install.packages("dplyr")
library(gridExtra) #install.packages("gridExtra")
library(jsonlite) #install.packages("jsonlite")
library(tidyverse) #install.packages("tidyverse")
# --------------------------------- #
```

####PLEASE load the main data sets in your environment. You can alter the code below

```{r}
#load("path/to/your/directory/prism_datasets.rda")
#load("path/to/your/directory/cellline_datasets.rda")
```


```{r}
####PLEASE load the extended data sets in your environment. You can alter the code below. You can find them in our github in 07_extdata or dare to use the functions below.
url <- "https://raw.githubusercontent.com/datascience-mobi-2023/topic05_team04/main/07_extdata/oncological_treatments.xlsx"
file1 <- "oncological_treatments.xlsx"
download.file(url, destfile = file1, mode = "wb")
cancer.therapy <- read_excel(file1, sheet = 1)

url1 <- "https://raw.githubusercontent.com/datascience-mobi-2023/topic05_team04/main/07_extdata/h.all.v2023.1.Hs.json.txt"
file2 <- "h.all.v2023.1.Hs.json.txt"
download.file(url1, destfile = file2, method = "auto")
downloaded_file_path2 <- file.path(getwd(), file2)
hallmarks <- fromJSON(downloaded_file_path2)
```

```{r}
## Checkt wie viele Zeilen und Spalten NA`s drin habe
sum(is.na(prism)) ##432639
sum(apply(prism, 1, function(x){any(is.na(x))})) ##481
sum(apply(prism, 2, function(x){any(is.na(x))})) ##11168

###############################
###### PRISM IMPUTATION ####### Luis
###############################
p_onlyNA.col <- colnames(prism[which(sapply(prism, class) == "logical")]) 
rem.pNAcol <- which(colnames(prism) %in% p_onlyNA.col)
prismNA <- prism[, -rem.pNAcol]
prism_imp <- as.data.frame(apply(prismNA, 2, function(x) {
    is_na <- is.na(x)
    x[is_na] <- mean(x, na.rm = TRUE)
    return(x)
})) 
######################################
###### BREAST PRISM IMPUTATION ####### Luis
######################################
breast_prism.cl <- prism.cl[which(prism.cl$lineage == 'breast'), ]
breast_prism <- prism[which(rownames(prism) %in% breast_prism.cl$DepMap_ID), ]
bp_onlyNA.col <- colnames(breast_prism[which(colSums(is.na(breast_prism)) == 22)]) 
rem.bpNAcol <- which(colnames(breast_prism) %in% bp_onlyNA.col)
breast_prism_imp <- breast_prism[, -rem.bpNAcol] 

breast_prism_imp <- as.data.frame(apply(breast_prism_imp, 2, function(x) {
    is_na <- is.na(x)
    x[is_na] <- mean(x, na.rm = TRUE)
    return(x)
}))

## Verteilung der NA`s
mean(colMeans(is.na(prism[,-rem.pNAcol]))) #0.07698 => 7.7% NA`s in jeder Spalte
hist(colMeans(is.na(prism[,-rem.pNAcol])), breaks = 100, xlab = "NA Anteil", main = "Histogramm der NA Anteile")
```

```{r}
#########################################
###### SELECT MOST EFFIZIENT DRUGS ###### Luis
#########################################
##############
### BREAST ###
##############
drugnames_b <- sub("::.*", "", colnames(breast_prism_imp))
concentration_b <- as.numeric(sub(".*::(.*?)::.*", "\\1", colnames(breast_prism_imp)))
names_conc_drug_b <- sub("::.*", "", sub("::", ":", colnames(breast_prism_imp)))
colMeans_breast <- apply(breast_prism_imp, 2, mean)
duplicate_drugs_b <- unique(drugnames_b[duplicated(drugnames_b)])
df_nam_con_mean_b <- data.frame(colMeans_breast, drugnames_b, concentration_b, names_conc_drug_b)
lowest_mean_duplicate_b <- data.frame()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    lowest_colmean_b <- min(act_df_b$colMeans_breast, na.rm = TRUE)
    lowest_mean_duplicate_b <- rbind(lowest_mean_duplicate_b, act_df_b[which(act_df_b$colMeans_breast == lowest_colmean_b),])
}
highest_mean_duplicate_b <- data.frame()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    highest_colmean_b <- max(act_df_b$colMeans_breast, na.rm = TRUE)
    highest_mean_duplicate_b <- rbind(highest_mean_duplicate_b , act_df_b[which(act_df_b$colMeans_breast == highest_colmean_b),])
}
pref_drug_con_combo_breast <- rownames(lowest_mean_duplicate_b)
breast_prism_lowest <- breast_prism_imp[,pref_drug_con_combo_breast]
lowest_mean_duplicate_tsh_b <- lowest_mean_duplicate_b[lowest_mean_duplicate_b$colMeans_breast < -2,]
pref_drug_ths_b <- rownames(lowest_mean_duplicate_tsh_b)
breast_prism_lowest_ths <- breast_prism_imp[,pref_drug_ths_b]
##############
### PRISM ####
##############
drugnames <- sub("::.*", "", colnames(prism_imp))
drugnames <- sub("::.*", "", colnames(prism_imp))
concentration <- as.numeric(sub(".*::(.*?)::.*", "\\1", colnames(prism_imp)))
names_conc_drug <- sub("::.*", "", sub("::", ":", colnames(prism_imp)))
colMeans <- apply(prism_imp, 2, mean)
duplicate_drugs <- unique(drugnames[duplicated(drugnames)])
df_nam_con_mean <- data.frame(colMeans, drugnames, concentration, names_conc_drug)
lowest_mean_duplicate <- data.frame()
for(i in 1:length(duplicate_drugs)) {
    act_rows <- which(df_nam_con_mean$drugnames == duplicate_drugs[i])
    act_df <- df_nam_con_mean[act_rows,]
    lowest_colmean <- min(act_df$colMeans, na.rm = TRUE)
    lowest_mean_duplicate <- rbind(lowest_mean_duplicate, act_df[which(act_df$colMeans == lowest_colmean),])
}
highest_mean_duplicate <- data.frame()
for(i in 1:length(duplicate_drugs)) {
    act_rows <- which(df_nam_con_mean$drugnames == duplicate_drugs[i])
    act_df <- df_nam_con_mean[act_rows,]
    highest_colmean <- max(act_df$colMeans, na.rm = TRUE)
    highest_mean_duplicate <- rbind(highest_mean_duplicate , act_df[which(act_df$colMeans == highest_colmean),])
}
pref_drug_con_combo <- rownames(lowest_mean_duplicate)
prism_lowest <- prism_imp[,pref_drug_con_combo]
lowest_mean_duplicate_tsh <- lowest_mean_duplicate[lowest_mean_duplicate$colMeans < -2,]
pref_drug_ths <- rownames(lowest_mean_duplicate_tsh)
prism_lowest_ths <- prism_imp[,pref_drug_ths]
```

```{r}
##############################
###### PRISM.CNV BREAST ###### Simon
##############################
breast_prism.cl <- prism.cl[which(prism.cl$lineage == 'breast'), ]
ID_breast_prism.cl <- breast_prism.cl$DepMap_ID
rows_breast_prism.cnv <- which(rownames(prism.cnv) %in% ID_breast_prism.cl)
breast_prism.cnv <- prism.cnv[rows_breast_prism.cnv, ]
```

```{r}
##############################
###### PRISM.EXP BREAST ###### Sharu
##############################
lineage.breast <- prism.cl[which(prism.cl$lineage == "breast"),]
breast_prism.exp <- prism.exp[which(rownames(prism.exp) %in% lineage.breast$DepMap_ID),]
breastzero.col <- apply(breast_prism.exp, 2, function(x) all(x == 0))
breast_PRISM.exp <- breast_prism.exp[, !breastzero.col]

```

```{r}
#############################
###### PRISM.ACHILLES ####### Aaron
#############################
###########################
### IMPUTATION & BREAST ###
###########################
prism.achilles.rm <-apply(prism.achilles, 2, function(x) {
  x[which(is.na(x))] <- median(x, na.rm = TRUE)
  return(x)
})
breast.cl <- which(prism.cl[,"lineage"] == "breast")
prism.achilles.breast <- prism.achilles.rm[rownames(prism.achilles.rm) %in% prism.cl[breast.cl, 1], ]
################
### Overview ###
################
prism.achilles.mean <- apply(prism.achilles.rm, 2, mean)
prism.achilles.median <- apply(prism.achilles.rm, 2, median)
prism.achilles.sd <- apply(prism.achilles.rm, 2, sd)
prism.achilles.min <- apply(prism.achilles.rm, 2, min)
prism.achilles.max <- apply(prism.achilles.rm, 2, max)
prism.achilles.overview <- cbind(prism.achilles.mean, prism.achilles.median, prism.achilles.sd, prism.achilles.min, prism.achilles.max)
colnames(prism.achilles.overview) <- c("mean", "median", "standard deviation", "minimum", "maximum")

hist(prism.achilles.overview[,1], main = "mean of all the prism.achilles genes", xlab = "mean")
hist(prism.achilles.overview[,2], main = "median of all the prism.achilles genes", xlab = "median")
hist(prism.achilles.overview[,3], main = "standard deviation of all the prism.achilles genes", xlab = "standard deviation")
hist(prism.achilles.overview[,4], main = "minimum of all the prism.achilles genes", xlab = "minimum")
hist(prism.achilles.overview[,5], main = "maximum of all the prism.achilles genes", xlab = "maximum")
```

```{r}
#for prism.exp

prism.exp.mean <- apply(prism.exp, 2, mean)
prism.exp.median <- apply(prism.exp, 2, median)
prism.exp.sd <- apply(prism.exp, 2, sd)
prism.exp.min <- apply(prism.exp , 2, min)
prism.exp.max <- apply(prism.exp, 2, max)
prism.exp.overview <- cbind(prism.exp.mean, prism.exp.median, prism.exp.sd, prism.exp.min, prism.exp.max)
colnames(prism.exp.overview) <- c("mean", "median", "standard deviation", "minimum", "maximum")

hist(prism.exp.overview[,1], main = "mean of all the prism.exp genes", xlab = "mean")
hist(prism.exp.overview[,2], main = "median of all the prism.exp genes", xlab = "median")
hist(prism.exp.overview[,3], main = "standard deviation of all the prism.exp genes", xlab = "standard deviation")
hist(prism.exp.overview[,4], main = "minimum of all the prism.exp genes", xlab = "minimum")
hist(prism.exp.overview[,5], main = "maximum of all the prism.exp genes", xlab = "maximum")
````

```{r}

#for prism.cnv

prism.cnv.mean <- apply(prism.cnv, 2, mean)
prism.cnv.median <- apply(prism.cnv, 2, median)
prism.cnv.sd <- apply(prism.cnv, 2, sd)
prism.cnv.min <- apply(prism.cnv , 2, min)
prism.cnv.max <- apply(prism.cnv, 2, max)
prism.cnv.overview <- cbind(prism.cnv.mean, prism.cnv.median, prism.cnv.sd, prism.cnv.min, prism.cnv.max)
colnames(prism.exp.overview) <- c("mean", "median", "standard deviation", "minimum", "maximum")

hist(prism.cnv.overview[,1], main = "mean of all the prism.cnv genes", xlab = "mean")
hist(prism.cnv.overview[,2], main = "median of all the prism.cnv genes", xlab = "median")
hist(prism.cnv.overview[,3], main = "standard deviation of all the prism.cnv genes", xlab = "standard deviation")
hist(prism.cnv.overview[,4], main = "minimum of all the prism.cnv genes", xlab = "minimum")
hist(prism.cnv.overview[,5], main = "maximum of all the prism.cnv genes", xlab = "maximum")

```

```{r}
##########################################
###### FILTERING NON-ONCOLOGY DRUGS ###### Aaron
##########################################
cancer.therapy <- as.data.frame(cancer.therapy)
treat.names <- as.data.frame(prism.treat$name)
drug.overlap <- apply(treat.names, 1, function(x){
  sum(cancer.therapy == x)
})
non.onco.treat <- prism.treat[-which(drug.overlap > 0),]
non.onco.treat <- non.onco.treat[-which("oncology" == non.onco.treat$disease.area),]
```

***prism.treat subset***

```{r}

prism.treat.test <-cbind(prism.treat, rownames(prism.treat))

prism.treat_subset <- prism.treat.test %>% separate_rows(target, sep = ",") 

treat.gene_list <- prism.treat_subset[, c(7, 12)]

```
```