```{r}
load("/Users/luisherfurth/Codenmachtspass/prism_datasets.rda")
load("/Users/luisherfurth/Codenmachtspass/cellline_datasets.rda")
```

Checkt wie viele Zeilen und Spalten NA`s drin haben
```{r}
sum(is.na(prism)) ##432639
sum(apply(prism, 1, function(x){any(is.na(x))})) ##481
sum(apply(prism, 2, function(x){any(is.na(x))})) ##11168
```
--> Macht kein Sinn dies Spalten mit NA`s zu löschen, weil es zu viele sind

```{r}
min(prism, na.rm = TRUE) ##-12.06536
max(prism, na.rm = TRUE) ##5.007653
length(which(prism == "0")) ## 0 => keine mit genau 0
```

```{r}
sum(apply(prism, 2, function(x){all(is.na(x))})) ## 43 Spalten mit nur NA`s
NA.col <- colnames(prism[which(sapply(prism, class) == "logical")]) ## Die 43 Spalten mit nur NA`s
rem.NAcol <- which(colnames(prism) %in% NA.col)
sum(is.na(prism[,-rem.NAcol])) ## 411956
```
--> 411956 NA`s in den restlichen Spalten


```{r}
mean(colMeans(is.na(prism[,-rem.NAcol]))) #0.07698 => 7.7% NA`s in jeder Spalte
hist(colMeans(is.na(prism[,-rem.NAcol])), breaks = 100, xlab = "NA Anteil", main = "Histogramm der NA Anteile")
```

```{r}
library(pheatmap)
sum(is.na(replace(prism, prism == "NA", NA)))
prismNA0 <- prism[, -rem.NAcol]
prismNA0 <- prismNA0[is.na(prismNA0)] <- 0

# Erstellen einer benutzerdefinierten Farbpalette mit schwarzer Farbe für Null-Werte und einer normalen Farbskala für alle anderen Werte
my_palette <- colorRampPalette(c("white", "red"), space = "rgb")(99)
my_palette <- c(my_palette, "black")
my_breaks <- seq(min(prismNA0, na.rm = TRUE), max(prismNA0, na.rm = TRUE), length.out = length(my_palette))

# Verwenden der benutzerdefinierte Farbpalette und Breaks in der heatmap
pheatmap(prismNA0, show_rownames = FALSE, show_colnames = FALSE, cluster_cols = FALSE, cluster_rows = FALSE,
         col = my_palette, breaks = my_breaks)
```

```{r}

```

```{r}
```
