# x. Gene Search Engine

```{r}
hallmarks <- fromJSON("~/Downloads/h.all.v2023.1.Hs.json.txt")

hallmarks.geneSym <- unlist(lapply(hallmarks, function(x) x$geneSymbols))

hallmarks.data <- as.data.frame(hallmarks.geneSym)

input_string <- rownames(hallmark.genes)[which(hallmark.genes$hallmarks.geneSym%in%w.genes.cancer[1])]

```


```{r}

geneSearchEngine <- function(x) {
  gene_name <- x
  cat("Searching for:", gene_name, "\n")
  
  achilles_value <- breast.achilles.mean[gene_name]
  exp_value <- breast_exp_mean[gene_name]
  cnv_value <- breast_cnv.mean[gene_name]
  
  if (gene_name %in% hist.targets$genes) {
    frequency_value <- hist.targets[hist.targets$genes == gene_name, "Freq"]
  } else {
    frequency_value <- "none"
  }
 
  
  if (gene_name %in% hallmark.genes$hallmarks.geneSym) {
    hall.output <- rownames(hallmark.genes)[which(hallmark.genes$hallmarks.geneSym %in% gene_name)]
    hall.transform <- extract_transform(hall.output)
    hallmark <- paste(hall.transform, collapse = ", ")
  } else {
    hallmark <- "none"
  }
  
  if (gene_name %in% breast_prism.snv$Hugo_Symbol) {
    mut.pos <- which(gene_name %in% prism.snv$Hugo_Symbol)
    mutation <- as.vector(prism.snv$Variant_Classification[mut.pos])
  } else {
    mutation <- "none"
  }
  
  if (gene_name %in% breast_prism.snv$Hugo_Symbol) {
    variant.anno <- which(gene_name %in% breast_prism.snv$Hugo_Symbol)
    annotation.var <- as.vector(breast_prism.snv$Variant_annotation[variant.anno])
  } else {
    annotation.var <- "none"
  }
  
  if (gene_name %in% prism.treat_subset$target) {
    names <- paste(names.target[which(targets.treat$target==gene_name)], collapse = ", ")
    treatments <- trimws(names, whitespace = "right")
  } else {
    treatments <- "none"
  }
  
  cat("Frequency Value:", frequency_value, "\n")
  cat("Achilles Value:", achilles_value, "\n")
  cat("Exp Value:", exp_value, "\n")
  cat("Cnv Value:", cnv_value, "\n")
  cat("Mutation:", mutation, "\n")
  cat("Hallmark:", hallmark, "\n")
  cat("Variant Annotation:", annotation.var, "\n")
  cat("Treatments:", treatments, "\n")
  cat("\n")
}

geneSearchEngine("ESR1")



```