###################################
## CODE DESCRIPTION IN USER FILES##
###################################

# -------------------------------- #
### Data cleanup and preparation ###
# -------------------------------- #
```{r Trust me run it}
# ----------- #
### Legend ###
# ----------- #
### 1. Libraries and Data
### 2. PRISM Imputation
### 3. Breast PRISM Imputation
### 4. Prism.cnv Breast
### 5. Select most efficient drugs
####### 5.1 Breast
####### 5.2 PRISM
### 6. Filtering non-oncology drugs
### 7. Variance treatment all cancer
### 8. TOP (x) MOA
####### 8.1 Breast
####### 8.2 PRISM
# ----------- #
#####################################
# 1. # IMPORT LIBRARIES & DATA ######
#####################################
library(ggplot2) #install.packages("ggplot2")
library(umap) #install.packages("umap")
library(readxl) #install.packages("readxl")
library(scales) #install.packages("scales")
library(dplyr)  #install.packages("dplyr")
#library(tidyverse) #install.packages("tidyverse")
# --------------------------------- #
load("/Users/luisherfurth/Codenmachtspass/Data/prism_datasets.rda")
load("/Users/luisherfurth/Codenmachtspass/Data/cellline_datasets.rda")
###############################
# 2. # PRISM IMPUTATION ####### Luis
###############################
p_onlyNA.col <- colnames(prism[which(sapply(prism, class) == "logical")]) 
rem.pNAcol <- which(colnames(prism) %in% p_onlyNA.col)
prismNA <- prism[, -rem.pNAcol]
prism_imp <- as.data.frame(apply(prismNA, 2, function(x) {
    is_na <- is.na(x)
    x[is_na] <- mean(x, na.rm = TRUE)
    return(x)
})) 
######################################
# 3. # BREAST PRISM IMPUTATION ####### Luis
######################################
breast_prism.cl <- prism.cl[which(prism.cl$lineage == 'breast'), ]
breast_prism <- prism[which(rownames(prism) %in% breast_prism.cl$DepMap_ID), ]
bp_onlyNA.col <- colnames(breast_prism[which(colSums(is.na(breast_prism)) == 22)]) 
rem.bpNAcol <- which(colnames(breast_prism) %in% bp_onlyNA.col)
breast_prism_imp <- breast_prism[, -rem.bpNAcol] 

breast_prism_imp <- as.data.frame(apply(breast_prism_imp, 2, function(x) {
    is_na <- is.na(x)
    x[is_na] <- mean(x, na.rm = TRUE)
    return(x)
}))
##############################
# 4. # PRISM.CNV BREAST ###### Simon
##############################
breast_prism.cl <- prism.cl[which(prism.cl$lineage == 'breast'), ]
ID_breast_prism.cl <- breast_prism.cl$DepMap_ID
rows_breast_prism.cnv <- which(rownames(prism.cnv) %in% ID_breast_prism.cl)
breast_prism.cnv <- prism.cnv[rows_breast_prism.cnv, ]
##############################
# 4. # PRISM.EXP BREAST ###### Sharu
##############################
lineage.breast <- prism.cl[which(prism.cl$lineage == "breast"),]
breast_prism.exp <- prism.exp[which(rownames(prism.exp) %in% lineage.breast$DepMap_ID),]
breastzero.col <- apply(breast_prism.exp, 2, function(x) all(x == 0))
breast_PRISM.exp <- breast_prism.exp[, !breastzero.col]
#############################
# 5. # PRISM.ACHILLES ####### Aaron
#############################
###########################
### IMPUTATION & BREAST ###
###########################
prism.achilles.rm <-apply(prism.achilles, 2, function(x) {
  x[which(is.na(x))] <- median(x, na.rm = TRUE)
  return(x)
})
prism.achilles.breast <- prism.achilles.rm[rownames(prism.achilles.rm) %in% breast_prism.cl, ]
################
### Overview ###
################
prism.achilles.mean <- apply(prism.achilles.rm, 2, mean)
prism.achilles.median <- apply(prism.achilles.rm, 2, median)
prism.achilles.sd <- apply(prism.achilles.rm, 2, sd)
prism.achilles.min <- apply(prism.achilles.rm, 2, min)
prism.achilles.max <- apply(prism.achilles.rm, 2, max)
prism.achilles.overview <- cbind(prism.achilles.mean, prism.achilles.median, prism.achilles.sd, prism.achilles.min, prism.achilles.max)
colnames(prism.achilles.overview) <- c("mean", "median", "standard deviation", "minimum", "maximum")
#########################################
# 5. # SELECT MOST EFFIZIENT DRUGS ###### Luis
#########################################
##############
### BREAST ###
##############
drugnames_b <- sub("::.*", "", colnames(breast_prism_imp))
concentration_b <- as.numeric(sub(".*::(.*?)::.*", "\\1", colnames(breast_prism_imp)))
names_conc_drug_b <- sub("::.*", "", sub("::", ":", colnames(breast_prism_imp)))
colMeans_breast <- apply(breast_prism_imp, 2, mean)
duplicate_drugs_b <- unique(drugnames_b[duplicated(drugnames_b)])
df_nam_con_mean_b <- data.frame(colMeans_breast, drugnames_b, concentration_b, names_conc_drug_b)
lowest_mean_duplicate_b <- data.frame()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    lowest_colmean_b <- min(act_df_b$colMeans_breast, na.rm = TRUE)
    lowest_mean_duplicate_b <- rbind(lowest_mean_duplicate_b, act_df_b[which(act_df_b$colMeans_breast == lowest_colmean_b),])
}
highest_mean_duplicate_b <- data.frame()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    highest_colmean_b <- max(act_df_b$colMeans_breast, na.rm = TRUE)
    highest_mean_duplicate_b <- rbind(highest_mean_duplicate_b , act_df_b[which(act_df_b$colMeans_breast == highest_colmean_b),])
}
pref_drug_con_combo_breast <- rownames(lowest_mean_duplicate_b)
breast_prism_lowest <- breast_prism_imp[,pref_drug_con_combo_breast]
lowest_mean_duplicate_tsh_b <- lowest_mean_duplicate_b[lowest_mean_duplicate_b$colMeans_breast < -2,]
pref_drug_ths_b <- rownames(lowest_mean_duplicate_tsh_b)
breast_prism_lowest_ths <- breast_prism_imp[,pref_drug_ths_b]
##############
### PRISM ####
##############
drugnames <- sub("::.*", "", colnames(prism_imp))
drugnames <- sub("::.*", "", colnames(prism_imp))
concentration <- as.numeric(sub(".*::(.*?)::.*", "\\1", colnames(prism_imp)))
names_conc_drug <- sub("::.*", "", sub("::", ":", colnames(prism_imp)))
colMeans <- apply(prism_imp, 2, mean)
duplicate_drugs <- unique(drugnames[duplicated(drugnames)])
df_nam_con_mean <- data.frame(colMeans, drugnames, concentration, names_conc_drug)
lowest_mean_duplicate <- data.frame()
for(i in 1:length(duplicate_drugs)) {
    act_rows <- which(df_nam_con_mean$drugnames == duplicate_drugs[i])
    act_df <- df_nam_con_mean[act_rows,]
    lowest_colmean <- min(act_df$colMeans, na.rm = TRUE)
    lowest_mean_duplicate <- rbind(lowest_mean_duplicate, act_df[which(act_df$colMeans == lowest_colmean),])
}
highest_mean_duplicate <- data.frame()
for(i in 1:length(duplicate_drugs)) {
    act_rows <- which(df_nam_con_mean$drugnames == duplicate_drugs[i])
    act_df <- df_nam_con_mean[act_rows,]
    highest_colmean <- max(act_df$colMeans, na.rm = TRUE)
    highest_mean_duplicate <- rbind(highest_mean_duplicate , act_df[which(act_df$colMeans == highest_colmean),])
}
pref_drug_con_combo <- rownames(lowest_mean_duplicate)
prism_lowest <- prism_imp[,pref_drug_con_combo]
lowest_mean_duplicate_tsh <- lowest_mean_duplicate[lowest_mean_duplicate$colMeans < -2,]
pref_drug_ths <- rownames(lowest_mean_duplicate_tsh)
prism_lowest_ths <- prism_imp[,pref_drug_ths]
##########################################
# 5. # FILTERING NON-ONCOLOGY DRUGS ###### Aaron
##########################################
cancer.therapy <- read_excel("/Users/luisherfurth/Codenmachtspass/Data/oncological_treatments.xlsx")
cancer.therapy <- as.data.frame(cancer.therapy)
treat.names <- as.data.frame(prism.treat$name)
drug.overlap <- apply(treat.names, 1, function(x){
  sum(cancer.therapy == x)
})
non.onco.treat <- prism.treat[-which(drug.overlap > 0),]
non.onco.treat <- non.onco.treat[-which("oncology" == non.onco.treat$disease.area),]
###########################################
# 7. # VARIANCE TREATMENT ALL CANCER ###### Aaron
###########################################
lineages <- unique(prism.cl$lineage)
lineages <- as.data.frame(lineages)
lineages.distribution <- apply(lineages, 1, function(x) {
    sum(prism.cl$lineage%in%x)
    })
rel.cl <- as.data.frame(lineages[which(lineages.distribution >= 10), ])
prism_var <- apply(prism_lowest, 1, var)
prism_var <- as.data.frame(prism_var)
prism.var.mean <- apply(rel.cl, 1, function(x){
  DepMap_ID <- prism.cl$DepMap_ID[prism.cl$lineage%in%x]
  test <- which(rownames(prism_var)%in%DepMap_ID)
  mean(prism_var[test,])
})
prism.var.mean <- as.data.frame(prism.var.mean)
names(prism.var.mean) <- "mean_of_variance"
number_of_cellines <- lineages.distribution[lineages.distribution >= 10]
prism.var.mean$Number_of_cellines <- number_of_cellines
########################################
# 8. # FACTOR FOR THE TOP (X) MOA ###### Luis
########################################
##############
### BREAST ###
##############
meta_eff_treat_b <- prism.treat[pref_drug_con_combo_breast,]
level_counts_b <- table(meta_eff_treat_b$moa)
sorted_levels_b <- names(sort(level_counts_b, decreasing = TRUE))
top_x_levels_b <- sorted_levels_b[1:20] ### <---! USER INPUT --->
levels_b <- factor(meta_eff_treat_b$moa, levels = c("Other", top_x_levels_b))
meta_eff_treat_b$levels_b <- levels_b
meta_eff_treat_b$levels_b[is.na(meta_eff_treat_b$levels_b)] <- "Other"
level_colors_b <- rainbow(length(top_x_levels_b))
color_palette_b <- c(setNames(level_colors_b, top_x_levels_b), Other = "transparent")
#############
### PRISM ###
#############
meta_eff_treat <- prism.treat[pref_drug_con_combo,]
level_counts <- table(meta_eff_treat$moa)
sorted_levels <- names(sort(level_counts, decreasing = TRUE))
top_x_levels <- sorted_levels[1:20]  ### <---! USER INPUT --->
levels <- factor(meta_eff_treat$moa, levels = c("Other", top_x_levels))
meta_eff_treat$levels <- levels
meta_eff_treat$levels[is.na(meta_eff_treat$levels)] <- "Other"
level_colors <- rainbow(length(top_x_levels))
color_palette <- c(setNames(level_colors, top_x_levels), Other = "lightgray")
####################################
# 9.1 # CORRELATION DRUG ~ CONC ###### Luis
####################################
##############
### BREAST ###
##############
drugnames_b <- sub("::.*", "", colnames(breast_prism_imp))
concentration_b <- as.numeric(sub(".*::(.*?)::.*", "\\1", colnames(breast_prism_imp)))
names_conc_drug_b <- sub("::.*", "", sub("::", ":", colnames(breast_prism_imp)))
colMeans_breast <- apply(breast_prism_imp, 2, mean)
duplicate_drugs_b <- unique(drugnames)
df_nam_con_mean_b <- data.frame(colMeans_breast, drugnames_b, concentration_b, names_conc_drug_b)
highest_cor_b <- data.frame()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    if (length(act_rows_b) > 2) {
        cor_b <- cor(act_df_b$concentration_b, act_df_b$colMeans_breast, method = "pearson")
        new_row <- data.frame(drugname = duplicate_drugs_b[i], correlation = cor_b)
        highest_cor_b <- rbind(highest_cor_b, new_row)
    }
}
###############################
# 9. # LINEAR REGRESSION ###### Luis
###############################
##############
### BREAST ###
##############
regression_list_b <- list()
r_squared_b <- c()
p_value_b <- c()
for(i in 1:length(duplicate_drugs_b)) {
    act_rows_b <- which(df_nam_con_mean_b$drugnames_b == duplicate_drugs_b[i])
    act_df_b <- df_nam_con_mean_b[act_rows_b,]
    if (length(act_rows_b) > 3) {
        act_reg_b <- lm(colMeans_breast ~ concentration_b, data = act_df_b)
        act_residuals_b <- act_reg_b$residuals
        act_shapiro_b <- shapiro.test(act_residuals_b)
        act_plot_b <- data.frame(concentration_b = act_df_b$concentration, colMeans = act_df_b$colMeans_breast)
        regression_list_b[[i]] <- list(Summary_reg = summary(act_reg_b), Model = act_reg_b, Residuals = act_residuals_b, R_squared = summary(act_reg_b)$r.squared, Plotdata = act_plot_b, Shapiro_test = act_shapiro_b, prediction = act_df_b)
        names(regression_list_b)[i] <- duplicate_drugs_b[i]
        r_squared_b <- c(r_squared_b, summary(act_reg_b)$r.squared)
        p_value_b <- c(p_value_b, act_shapiro_b$p.value)
    }
}
testname <- "BRD-K99383816-001-03-5"
#######################
### PLOT REGRESSION ###
#######################
plot_reg <- function(drugname) {
    position <- which(drugname == names(regression_list_b))
    #### Summary model ####
    act_summary_b <- regression_list_b[[position]][[2]]
    #### Model ####
    act_model_b <- regression_list_b[[position]][[1]]
    #### Shapiro-Wilk test ####
    act_shapiro <- regression_list_b[[position]][[6]]

    #### Metadata ####
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
    list(a = format(unname(coef(act_model_b)[1]), digits = 2),
         b = format(unname(coef(act_model_b)[2]), digits = 2),
         r2 = format(act_model_b$r.squared, digits = 3)))
    as.character(as.expression(eq))

    #### Plot the regression ####
    ggplot <- ggplot(data = regression_list_b[[position]][[5]], aes(x = concentration_b, y = colMeans)) +
        stat_smooth(method = "lm", formula = y ~ x, geom = "smooth") +
        geom_point() +
        labs(x = "Concentration", y = "Mean of PRISM score", title = paste("Regression for:", drugname)) +
        annotate("text", x = 6.5, y = 1.5, label = eq, size = 3) +
        annotate("text", x = 6.5, y = 1, label = paste("Shapiro-Wilk normality test for Residuals:", "\n", "W =", round(act_shapiro$statistic, 3), "|  p-value =", format(act_shapiro$p.value, scientific = TRUE)), size = 3)

    return(ggplot)
}
#######################
### PREDICTION TOOL ###
#######################
prediction_tool <- function(drugname, conc_values) {

    position <- which(drugname == names(regression_list_b))

    #### Prediction ####
    act_model_b <- regression_list_b[[position]][[2]]
    new_data <- data.frame(concentration_b = conc_values) 
    act_shapiro <- regression_list_b[[position]][[6]]
    colMeans <- predict(act_model_b, newdata = new_data)

    cat("-------------------------------------------------------\n")
    cat("Concentrations:\n")
    print(setNames(conc_values, c(1:length(conc_values))))
    cat("Predicted Prism Scores:\n")
    print(round(colMeans, 3))
    cat("-------------------------------------------------------\n")

    ### Combine the data ###
    act_newdata <- cbind(new_data, colMeans)
    act_newdata <- cbind(act_newdata, level = c(replicate(length(new_data), "predicted")))
    hold_df <- cbind(regression_list_b[[position]][[5]], level = c(replicate(length(regression_list_b[[position]][[5]]$concentration_b), "original")))
    comb_df <- rbind(hold_df, act_newdata)
    comb_df[,3] <- as.factor(comb_df[,3])
    col_df <- c(predicted = "coral2", original = "black")

    ### Metadata ###
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
    list(a = format(unname(coef(act_model_b)[1]), digits = 2),
         b = format(unname(coef(act_model_b)[2]), digits = 2),
         r2 = format(summary(act_model_b)$r.squared, digits = 3)))
    as.character(as.expression(eq))

    ### Plot the prediction ###
    ggplot <- ggplot(data = comb_df, aes(x = concentration_b, y = colMeans, color = level)) +
        stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", color = "steelblue") +
        geom_point() +
        labs(x = "Concentration", y = "Mean of PRISM score", title = paste("Regression for:", drugname), color = "") +
        scale_color_manual(values = col_df) +
        annotate("text", x = 6.5, y = 1.5, label = eq, size = 3) +
        annotate("text", x = 6.5, y = 1, label = paste("Shapiro-Wilk normality test for Residuals:", "\n", "W =", round(act_shapiro$statistic, 3), "|  p-value =", format(act_shapiro$p.value, scientific = TRUE)), size = 3)

    return(ggplot)
}
```

# --------------------------- #
### Variables and their use ###
# --------------------------- #
```{r}
prediction_tool(testname, c(0.1, 0.5, 1, 2, 5, 10))
#############
# IMPORTANT #
#############
prism_imp #<--! prism with NA´s imputed -->
breast_prism_imp #<--! subset breast cancer with NA´s imputed -->
lowest_mean_duplicate #<--! drug, conc, colMean for the most effizient drugs -->
breast_prism_lowest #<--! most efficient drugs for breast cellines -->
# -> breast_prism_lowest_ths #<--! with threshold (threshold: -2) -->
prism_lowest #<--! most efficient drugs for all cellines -->
# ->prism_lowest_ths #<--! with threshold (threshold: -2) -->
prism.achilles.overview #<--! almost all celllines K.O. Score (min, max, mean, etc...) -->
prism.achilles.breast #<--! breast cancer celllines K.O. Score -->
################
# NICE TO HAVE #
################
meta_eff_treat_b #<--! meta data for most effizient drugs breast -->
meta_eff_treat #<--! same for all cellines -->
top_x_levels_b #<--! top x moa for breast -->
top_x_levels #<--! same all cellines -->
```

# -------------------------------------- #
### Basic statistics and Visualisation ###
# -------------------------------------- #
```{r}
################################
###### NA ANALYSIS #############
################################
sum(is.na(prism))
min(prism, na.rm = TRUE) ##-12.06536
max(prism, na.rm = TRUE) ##5.007653
hist(colMeans(is.na(prism[,-rem.pNAcol])), breaks = 100, xlab = "NA Anteil", main = "Histogramm der NA Anteile")
################################
###### CELL GROWTH BREAST ######
################################
vec_breast <- unlist(sapply(breast_prism, function(x) x[is.numeric(x)]))
vec_breast <- as.data.frame(na.omit(vec_breast))
hist(vec_breast, breaks = 80, xlab = "Cell Growth", main = "Overview of the Cell Growth", xlim = c(-8, 2));abline(v = mean(vec_breast, na.rm = TRUE), col = "red", lwd = 2, lty = 3);abline(v = median(vec_breast, na.rm = TRUE), col = "blue", lwd = 2, lty= 3);legend("topleft", legend = c("mean", "median"), col = c("red", "blue"), lwd = 2, lty = 3)
heatmapbreast <- pheatmap(breast_prism_imp, show_rownames = TRUE, show_colnames = FALSE)
##################################
###### CONCENTRATION EFFECT ######
##################################
hist(as.numeric(lowest_mean_duplicate_b$concentration_b))
hist(lowest_mean_duplicate_b$colMeans_breast)
hist(as.numeric(highest_mean_duplicate_b$concentration_b))
hist(highest_mean_duplicate_b$colMeans_breast)
#################################
###### DIMENSION REDUCTION ######
#################################
############
### UMAP ###
############
# ------
# BREAST
breast_cancer_umap <- umap(t(breast_prism_lowest), n_neighbors = 7, min_dist = 0.5, n_epochs = 200, n_components = 2) 
umap_layout_breast <- as.data.frame(breast_cancer_umap$layout)

umap_layout_breast$levels_b <- meta_eff_treat_b$levels_b

umap_layout_breast <- umap_layout_breast %>%
  mutate(alpha_level_b = ifelse(levels_b == "Other", 0.2, 1))

color_palette_b <- c(setNames(level_colors, top_x_levels), Other = "lightgray")

ggplot(umap_layout_breast, aes(x = V1, y = V2, color = levels_b, alpha = alpha_level_b)) +
    geom_point(size = 3) +
    scale_color_manual(values = color_palette_b) +
    theme_bw() +
    ggtitle("UMAP of the Breastcancer celllines")
# ------
# PRISM
cancer_umap <- umap(t(prism_lowest), n_neighbors = 7, min_dist = 0.5, n_epochs = 200, n_components = 2) 
umap_layout_prism <- as.data.frame(cancer_umap$layout)

umap_layout_prism$levels <- meta_eff_treat$levels

umap_layout_prism <- umap_layout_prism %>%
  mutate(alpha_level = ifelse(levels == "Other", 0.2, 1))

color_palette <- c(setNames(level_colors_b, top_x_levels_b), Other = "lightgray")

ggplot(umap_layout_prism, aes(x = V1, y = V2, color = levels, alpha = alpha_level)) +
    geom_point(size = 3) +
    scale_color_manual(values = color_palette) +
    theme_bw() +
    ggtitle("UMAP of all celllines")
# -----
#################################
###### Lineare Regression #######
#################################
# ------
special_drugs <- rownames(lowest_mean_duplicate_b[which(lowest_mean_duplicate_b$colMeans_breast < -2 & lowest_mean_duplicate_b$concentration_b < 1),])
special_drugs_meta <- meta_eff_treat_b[which(rownames(meta_eff_treat_b) %in% special_drugs),]
special_drugs_meta[,1:6]
special_drugs_meta[,7:12]
# ------ 
high_conc <- rownames(prism.treat[which(prism.treat$dose > 9),])
high_conc_breast <- breast_prism_imp[,which(colnames(breast_prism_imp) %in% high_conc)]
col_mean_high_conc <- apply(high_conc_breast, 2, mean)
# vvvvvvvv #
hist(col_mean_high_conc) # <---! distribution of the mean of the high concentration drugs -->
# ------
conc_tsh_b <- df_nam_con_mean_b$concentration_b[which(df_nam_con_mean_b$colMeans < -2)]
colMeans_tsh_b <- df_nam_con_mean_b$colMeans_breast[which(df_nam_con_mean_b$colMeans < -2)]
model_breast_tsh <- lm(colMeans_tsh_b ~ conc_tsh_b, data = df_nam_con_mean_b)
# vvvvvvvv #
summary(model_breast_tsh)
plot(conc_tsh_b, colMeans_tsh_b) ; abline(model_breast_tsh, col = "red") # <---! linear regression of the inhibitory drugs -->
# ------
model_breast <- lm(concentration_b ~ colMeans_breast, data = df_nam_con_mean_b)
model_prism <- lm(concentration ~ colMeans, data = df_nam_con_mean)
# vvvvvvvv #
plot(colMeans_breast,concentration_b); abline(model_breast, col = "red")
plot(colMeans,concentration); abline(model_prism, col = "red")
summary(model_breast) # <---! linear regression of the drugs on breast-->
summary(model_prism) # <---! linear regression of the drugs on prism-->
```

```{r}
######################
### VISUALISATIONS ###
######################
# --------------------------- #
### Concentraion comparison ###
# -------------------------- #
#hist(as.numeric(lowest_mean_duplicate_b$concentration_b))
#### Plot 1
ggplot1 <- ggplot() +
    geom_histogram(aes(x = lowest_mean_duplicate_b$concentration_b), bins = 10, fill = "coral") + 
    labs(title = "Lowest average prism score", x = "Concentration", y = "Count")
#hist(as.numeric(highest_mean_duplicate_b$concentration_b))
#### Plot 2
ggplot2 <- ggplot() +
    geom_histogram(aes(x = highest_mean_duplicate_b$concentration_b), bins = 10, fill = "steelblue") + 
    labs(title = "Highest average prism score", x = "Concentration", y = "Count")

grid.arrange(ggplot1, ggplot2, nrow = 1)
# --------------------------------- #
### Cell Growth of filtered drugs ###
# --------------------------------- #
#### Plot 3
inhibitory_fil <- lowest_mean_duplicate_b$colMeans_breast < -2
ggplot() +
    geom_histogram(aes(x = lowest_mean_duplicate_b$colMeans_breast, fill = inhibitory_fil), bins = 30) +
    labs(title = "Cell Growth of filtered drugs", x = "log2FC", y = "Count", fill = "Inhibitory") +
    scale_fill_discrete(labels = c("> -2", "< -2")) +
    scale_fill_manual(values = c("coral", "steelblue2"))
# ---------------------------- #
### Cell Growth of all drugs ###
# ---------------------------- #
vec_breast <- unlist(sapply(breast_prism, function(x) x[is.numeric(x)]))
vec_breast <- na.omit(vec_breast)
inhibitory <- vec_breast < -2
ggplot() +
    geom_histogram(aes(x = vec_breast, fill = inhibitory), bins = 111) +
    scale_fill_manual(values = c("coral2", "steelblue2")) +
    labs(title = "Cell Growth of breast cancer cells after treatment", x = "log2FC", y = "Count")

# ------------------------------------ #
### Correlation drug ~ concentration ###
# ------------------------------------ #
high_cor <- highest_cor_b$correlation < -0.7
ggplot() +
    geom_histogram(aes(x = highest_cor_b$correlation, fill = high_cor), bins = 75) +
    labs(title = "Correlation of drug and concentration", x = "Pearson Correlation", y = "Count", fill = " ") +
    scale_fill_discrete(labels = c("> 0.7", "< 0.7")) 
# -------------------------------------- #
### UMAP of most effizient drugs prism ###
# -------------------------------------- #
cancer_umap <- umap(t(prism_lowest), n_neighbors = 7, min_dist = 0.5, n_epochs = 200, n_components = 2) 
umap_layout_prism <- as.data.frame(cancer_umap$layout)

umap_layout_prism$levels <- meta_eff_treat$levels

umap_layout_prism <- umap_layout_prism %>%
  mutate(alpha_level = ifelse(levels == "Other", 0.2, 1))

color_palette <- c(setNames(level_colors_b, top_x_levels_b), Other = "lightgray")

ggplot(umap_layout_prism, aes(x = V1, y = V2, color = levels, alpha = alpha_level)) +
    geom_point(size = 3) +
    scale_color_manual(values = color_palette) +
    theme_bw() +
    ggtitle("UMAP of all celllines")
# ------------------------------------------ #
### Histogramm of r_squared of regressions ###
# ------------------------------------------ #
ggplot() +
    geom_histogram(aes(x = r_squared_b), bins = 75, fill = "steelblue") +
    labs(title = "R^2 of linear regressions for every treatment", x = "R^2 value", y = "Count")
# ---------------------------------------- #
### Histogramm of p_value of regressions ###
# ---------------------------------------- #
singificance_b <- p_value_b > 0.05
ggplot() +
    geom_histogram(aes(x = p_value_b, fill = singificance_b), bins = 75) +
    labs(title = "Distribution of p-values of the Shapiro-test performed on all models", x = "p-value", y = "Count", fill = "") +
    scale_fill_discrete(labels = c("< 0.05", "non significant")) 
```
## Testing
```{r}
#### Select high correlation drugs ####
low_cor_b <- highest_cor_b[which(highest_cor_b$correlation < - 0.9),]
low_cor_drug_b <- low_cor_b$drugname

#### Linear regression of the high correlation drugs ####
df_nam_con_mean_b[which(low_cor_drug_b %in% df_nam_con_mean_b$drugnames_b),]
colme_low_cor_b <- df_nam_con_mean_b$colMeans_breast[which(low_cor_drug_b %in% df_nam_con_mean_b$drugnames_b)]
conc_low_cor_b <- df_nam_con_mean_b$concentration_b[which(low_cor_drug_b %in% df_nam_con_mean_b$drugnames_b)]

cor_model <- lm(colme_low_cor_b ~ conc_low_cor_b, data = df_nam_con_mean_b)
summary(cor_model)

plot(conc_low_cor_b, colme_low_cor_b); abline(cor_model, col = "red")

#### drugs with correlation -1 ####
min(highest_cor_b$correlation)
df_nam_con_mean_b[which(highest_cor_b$drugname[which(highest_cor_b$correlation == min(highest_cor_b$correlation))] %in% df_nam_con_mean_b$drugnames_b),]
```

